services:
  nodejs:
    image: node_consulta_credito
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
     - ./db-consulta_credito:/var/lib/postgresql/data
    ports:
      - "5432:5432"
